name: base
channels:
  - conda-forge
dependencies:
  - ase=3.23.0
  - atomistics=0.1.30
  - black=24.4.2
  - conda-smithy=3.36.2
  - coverage=7.5.4
  - dynaphopy=1.17.15
  - ffmpeg=4.3.2
  - git=2.45.1
  - git-filter-repo=2.38.0
  - gmailsorter=0.1.3
  - graphviz=11.0.0
  - grayskull=2.5.3
  - gunicorn=22.0.0
  - h5io=0.2.3
  - h5io_browser=0.0.15
  - iprpy-data=2023.07.25
  - jupyterlab=4.2.2
  - lammps=2024.02.07=*openmpi*
  - langchain=0.2.6
  - langchain-experimental=0.0.62
  - langchain-openai=0.1.10
  - matplotlib-base=3.8.4
  - mkl=2023.2.0
  - mpi4py=3.1.6
  - pyauthenticator=0.2.0
  - pygraphviz=1.13
  - pyiron=0.5.2
  - pyiron-data=0.0.29
  - pyiron_atomistics=0.6.3
  - pyiron_base=0.9.5
  - pymace=0.3.5
  - pymov2gif=0.0.2
  - pympipool=0.8.5
  - pysqa=0.1.21
  - python=3.12.4
  - python-ternary=1.0.8
  - pytorch=2.1.2
  - qe=7.0
  - seaborn=0.13.2
  - sqsgenerator=0.3
  - tensorflow=2.16.1
  - wget=1.21.4
