channels:
  - conda-forge
dependencies:
  - atomistics=0.1.19
  - black=23.12.1
  - coverage=7.4.0
  - dynaphopy=1.17.15
  - ghostscript=10.02.1
  - gifsicle=1.94
  - git=2.43.0
  - grayskull=2.5.2
  - h5io=0.1.10
  - jupyterlab=4.0.10
  - lammps=2023.08.02
  - mamba=1.5.6
  - matgl=0.9.1
  - matplotlib-base=3.8.2
  - mpi4py=3.1.5
  - nglview=3.0.8
  - numpy=1.26.2
  - openmpi=4.1.6
  - paramiko=3.4.0
  - phonopy=2.21.0
  - pyauthenticator=0.2.0
  - pyfileindex=0.0.19
  - pygraphviz=1.11
  - pyiron=0.5.1
  - pyiron-data=0.0.26
  - pyiron_atomistics=0.3.8
  - pyiron_base=0.6.16
  - pyiron_gpl=0.0.4
  - pylammpsmpi=0.2.10
  - pymatgen=2023.12.18
  - pymov2gif=0.0.2
  - pympipool=0.7.9
  - pyscal=2.10.18
  - pysqa=0.1.8
  - python=3.11.7
  - pytube=15.0.0
  - pyxtal=0.6.1
  - qe=7.0
  - seekpath=2.1.0
  - spglib=2.2.0
  - sqsgenerator=0.3
  - structuretoolkit=0.0.15
  - tqdm=4.66.1
  - twine=4.0.2
  - versioneer=0.29
  - wget=1.20.3
  - yfinance=0.2.33
  - zeromq=4.3.5
