name: general-osx-64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.12"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: .ci_support/environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        python .ci_support/dryrun.py generalenv_requirements/environment.yml env-osx-x64.yml 
    - uses: actions/upload-artifact@v4
      with:
        path: env-osx-x64.yml
