name: macos-x64

on:
  pull_request:

jobs:
  build_environment:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.12"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: .ci_support/environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        ./.ci_support/convert-macos.sh
        cat environment.yml
        python .ci_support/dryrun.py environment.yml env-osx-x64.yml 
    - uses: actions/upload-artifact@v4
      with:
        path: env-osx-x64.yml

  build_constructor:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: "3.12"
        mamba-version: "*"
        channels: conda-forge
        miniforge-variant: Mambaforge
        channel-priority: strict
        auto-update-conda: true
    - name: Build Constructor
      shell: bash -l {0}
      run: |
        conda install -y --name test -c conda-forge constructor
        mkdir build
        ./.ci_support/convert-macos.sh
        cat environment.yml
        constructor -v --output-dir=build --platform="osx-64" constructor
